version: "3.9"

services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: the_funny
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build: .
    command: npm run dev
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/the_funny
      NEXTAUTH_URL: http://localhost:3000
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  db-data:
