version: "3.9"

services:
  web:
    build: .
    command: npm run dev
    environment:
      SESSION_SECRET: change-me
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
