import { promises as fs } from "node:fs";
import path from "node:path";
import {
  type AdSlotRecord,
  type BookingRecord,
  type ComedianAppearanceRecord,
  type ComedianProfileRecord,
  type ComedianVideoRecord,
  type ConversationReviewRecord,
  type DatabaseSnapshot,
  type GigRecord,
  type MessageRecord,
  type OfferRecord,
  type PromoterProfileRecord,
  type ReviewRecord,
  type ThreadRecord,
  type UserRecord,
  type VenueProfileRecord,
  type AvailabilityRecord,
} from "@/types/database";
import { FeatureFlagKey, getDefaultFeatureFlags } from "@/lib/config/flags";

const DATA_PATH = path.join(process.cwd(), "data", "database.json");
const HASHED_PASSWORD = "$2a$10$NSAXdlvRg.IVwMnoneGfMOmzMDy3JWta4qTJPUJWtfNK14Zj.NfLa"; // DemoPass123!

const iso = (value: string): string => new Date(value).toISOString();
const date = (month: number, day: number, hour = 12): string =>
  iso(`2024-${String(month).padStart(2, "0")}-${String(day).padStart(2, "0")}T${String(hour).padStart(2, "0")}:00:00Z`);

const users: UserRecord[] = [
  {
    id: "user-admin",
    name: "Alex Admin",
    email: "admin@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "ADMIN",
    createdAt: date(1, 1, 9),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-promoter-seattle",
    name: "Sasha Showcase",
    email: "seattle.promoter@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "PROMOTER",
    createdAt: date(1, 3, 10),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-promoter-portland",
    name: "Parker PDX",
    email: "portland.promoter@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "PROMOTER",
    createdAt: date(1, 4, 11),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-promoter-tacoma",
    name: "Taylor Tacoma",
    email: "tacoma.promoter@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "PROMOTER",
    createdAt: date(1, 5, 12),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-promoter-olympia",
    name: "Oakley Olympia",
    email: "olympia.promoter@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "PROMOTER",
    createdAt: date(1, 6, 13),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-venue-seattle-laugh-lodge",
    name: "Laugh Lodge",
    email: "laugh.lodge@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "VENUE",
    createdAt: date(1, 7, 14),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-venue-seattle-bay",
    name: "Bayfront Comedy",
    email: "bayfront@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "VENUE",
    createdAt: date(1, 7, 16),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-venue-portland-stumptown",
    name: "Stumptown Laugh Lab",
    email: "stumptown@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "VENUE",
    createdAt: date(1, 8, 9),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-venue-portland-bridge",
    name: "Bridge City Comedy",
    email: "bridgecity@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "VENUE",
    createdAt: date(1, 8, 11),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-venue-tacoma-grit",
    name: "Grit City Stage",
    email: "gritcity@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "VENUE",
    createdAt: date(1, 9, 10),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-venue-tacoma-waterfront",
    name: "Waterfront Comedy Loft",
    email: "waterfront@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "VENUE",
    createdAt: date(1, 9, 12),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-venue-olympia-capitol",
    name: "Capitol City Club",
    email: "capitolcity@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "VENUE",
    createdAt: date(1, 10, 10),
    isPremium: false,
    premiumSince: null,
  },
  {
    id: "user-venue-olympia-brew",
    name: "Brew HaHa Hall",
    email: "brewhaha@thefunny.local",
    hashedPassword: HASHED_PASSWORD,
    role: "VENUE",
    createdAt: date(1, 10, 12),
    isPremium: false,
    premiumSince: null,
  },
];

interface ComedianSeed {
  id: string;
  name: string;
  email: string;
  stageName: string;
  city: string;
  state: string;
  styles: string[];
  cleanRating: "CLEAN" | "PG13" | "R";
  rateMin: number;
  rateMax: number;
  bio: string;
  credits: string[];
  reels: string[];
  photos: string[];
  notableClubs: string[];
  instagram?: string;
  tiktok?: string;
  youtube?: string;
  premium?: boolean;
}

const comedianSeeds: ComedianSeed[] = [
  {
    id: "user-comedian-ava",
    name: "Ava Ashland",
    email: "ava@thefunny.local",
    stageName: "Ava Ashland",
    city: "Seattle",
    state: "WA",
    styles: ["Storytelling", "Observational", "PNW references"],
    cleanRating: "PG13",
    rateMin: 350,
    rateMax: 600,
    bio: "Seattle-based storyteller blending outdoor adventures with sharp punchlines.",
    credits: ["SketchFest Seattle", "Timber Comedy Festival"],
    reels: ["https://youtu.be/ava-ashland-reel"],
    photos: ["https://images.unsplash.com/photo-1524504388940-b1c1722653e1"],
    notableClubs: ["Laughs Comedy Club", "Capitol Cider"],
    instagram: "@avaashland",
    tiktok: "@avaashlandcomedy",
    youtube: "https://www.youtube.com/@avaashland",
    premium: true,
  },
  {
    id: "user-comedian-ben",
    name: "Ben Beacon",
    email: "ben@thefunny.local",
    stageName: "Ben Beacon",
    city: "Portland",
    state: "OR",
    styles: ["Alt", "Deadpan"],
    cleanRating: "PG13",
    rateMin: 300,
    rateMax: 550,
    bio: "Portland barista-turned-comic known for dry takes on tech and tiny homes.",
    credits: ["Bridgetown Comedy Festival", "Keep Portland Funny"],
    reels: ["https://youtu.be/ben-beacon-reel"],
    photos: ["https://images.unsplash.com/photo-1551122101-0d21b06ae8b9"],
    notableClubs: ["Helium Portland", "Funhouse Lounge"],
    instagram: "@benbeacon",
    youtube: "https://www.youtube.com/@benbeacon",
  },
  {
    id: "user-comedian-cara",
    name: "Cara Cascade",
    email: "cara@thefunny.local",
    stageName: "Cara Cascade",
    city: "Tacoma",
    state: "WA",
    styles: ["High energy", "Crowd work"],
    cleanRating: "R",
    rateMin: 400,
    rateMax: 750,
    bio: "Tacoma club favorite bringing contagious energy and sharp crowd work skills.",
    credits: ["Seattle International Comedy Competition"],
    reels: ["https://youtu.be/cara-cascade-reel"],
    photos: ["https://images.unsplash.com/photo-1545239351-1141bd82e8a6"],
    notableClubs: ["Tacoma Comedy Club", "Jazzbones"],
    instagram: "@caracascade",
    tiktok: "@caracascade",
  },
  {
    id: "user-comedian-diego",
    name: "Diego Drift",
    email: "diego@thefunny.local",
    stageName: "Diego Drift",
    city: "Olympia",
    state: "WA",
    styles: ["Improvisational", "Character"],
    cleanRating: "PG13",
    rateMin: 250,
    rateMax: 500,
    bio: "Olympia improv pro mixing quirky characters with heartfelt stories.",
    credits: ["Northwest Black Comedy Festival"],
    reels: ["https://youtu.be/diego-drift-reel"],
    photos: ["https://images.unsplash.com/photo-1544723795-3fb6469f5b39"],
    notableClubs: ["Capitol City Club", "The Brotherhood Lounge"],
  },
  {
    id: "user-comedian-ella",
    name: "Ella Evergreen",
    email: "ella@thefunny.local",
    stageName: "Ella Evergreen",
    city: "Seattle",
    state: "WA",
    styles: ["Clean", "Corporate"],
    cleanRating: "CLEAN",
    rateMin: 500,
    rateMax: 900,
    bio: "Corporate-friendly comic with razor sharp crowd insights and musical tags.",
    credits: ["Microsoft Corporate Events", "Bumbershoot"],
    reels: ["https://youtu.be/ella-evergreen-reel"],
    photos: ["https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4"],
    notableClubs: ["Laughs Comedy Club", "Unexpected Productions"],
    instagram: "@ellaevergreen",
    tiktok: "@ellaevergreen",
    premium: true,
  },
  {
    id: "user-comedian-fern",
    name: "Fern Fox",
    email: "fern@thefunny.local",
    stageName: "Fern Fox",
    city: "Portland",
    state: "OR",
    styles: ["Storytelling", "Alternative"],
    cleanRating: "PG13",
    rateMin: 280,
    rateMax: 520,
    bio: "Story-driven comic weaving activism with whimsical PNW tales.",
    credits: ["Portland's Queer Comedy Fest"],
    reels: ["https://youtu.be/fern-fox-reel"],
    photos: ["https://images.unsplash.com/photo-1517841905240-472988babdf9"],
    notableClubs: ["Helium Portland", "Kelly's Olympian"],
  },
  {
    id: "user-comedian-gabe",
    name: "Gabe Glacier",
    email: "gabe@thefunny.local",
    stageName: "Gabe Glacier",
    city: "Bellingham",
    state: "WA",
    styles: ["Deadpan", "Surreal"],
    cleanRating: "PG13",
    rateMin: 220,
    rateMax: 450,
    bio: "Bellingham weirdo comic exploring cryptids, co-ops, and climate anxieties.",
    credits: ["Subdued Stringband Jamboree", "NW Fresh Faces"],
    reels: ["https://youtu.be/gabe-glacier-reel"],
    photos: ["https://images.unsplash.com/photo-1525134479668-1bee5c7c6845"],
    notableClubs: ["Upfront Theatre", "Make.Shift"],
  },
  {
    id: "user-comedian-hana",
    name: "Hana Harbor",
    email: "hana@thefunny.local",
    stageName: "Hana Harbor",
    city: "Seattle",
    state: "WA",
    styles: ["Clean", "Musical"],
    cleanRating: "CLEAN",
    rateMin: 450,
    rateMax: 850,
    bio: "Music-forward comic blending ukulele songs with heartfelt jokes.",
    credits: ["SketchFest Seattle", "Seattle Symphony Late Night"],
    reels: ["https://youtu.be/hana-harbor-reel"],
    photos: ["https://images.unsplash.com/photo-1515378791036-0648a3ef77b2"],
    notableClubs: ["Comedy/Bar Seattle", "The Crocodile"],
    instagram: "@hanaharbor",
    premium: true,
  },
  {
    id: "user-comedian-isa",
    name: "Isa Inland",
    email: "isa@thefunny.local",
    stageName: "Isa Inland",
    city: "Spokane",
    state: "WA",
    styles: ["Crowd work", "Storytelling"],
    cleanRating: "PG13",
    rateMin: 260,
    rateMax: 480,
    bio: "Road-tested Spokane comic who shines at casinos and breweries alike.",
    credits: ["Spokane Comedy Club", "Nate Jackson's Super Funny"],
    reels: ["https://youtu.be/isa-inland-reel"],
    photos: ["https://images.unsplash.com/photo-1517976487492-5750f3195933"],
    notableClubs: ["Spokane Comedy Club", "Tacoma Comedy Club"],
  },
  {
    id: "user-comedian-jules",
    name: "Jules Jetty",
    email: "jules@thefunny.local",
    stageName: "Jules Jetty",
    city: "Portland",
    state: "OR",
    styles: ["Riffing", "Satire"],
    cleanRating: "R",
    rateMin: 320,
    rateMax: 600,
    bio: "Sharp satire on sustainability and cycling culture, perfect for club weekends.",
    credits: ["Pickathon Laugh Stage"],
    reels: ["https://youtu.be/jules-jetty-reel"],
    photos: ["https://images.unsplash.com/photo-1521572267360-ee0c2909d518"],
    notableClubs: ["Helium Portland", "Curious Comedy"],
  },
  {
    id: "user-comedian-kai",
    name: "Kai Kettle",
    email: "kai@thefunny.local",
    stageName: "Kai Kettle",
    city: "Olympia",
    state: "WA",
    styles: ["Clean", "Improvisational"],
    cleanRating: "CLEAN",
    rateMin: 240,
    rateMax: 420,
    bio: "Improviser and emcee bringing welcoming vibes to breweries and fundraisers.",
    credits: ["OlyComedy Fest"],
    reels: ["https://youtu.be/kai-kettle-reel"],
    photos: ["https://images.unsplash.com/photo-1489515217757-5fd1be406fef"],
    notableClubs: ["Capitol City Club", "Rhythms Coffee"],
  },
  {
    id: "user-comedian-lena",
    name: "Lena Lighthouse",
    email: "lena@thefunny.local",
    stageName: "Lena Lighthouse",
    city: "Seattle",
    state: "WA",
    styles: ["Clean", "Corporate", "Storytelling"],
    cleanRating: "CLEAN",
    rateMin: 550,
    rateMax: 950,
    bio: "Former tech lead delivering clean, clever keynotes and comedy for corporate crowds.",
    credits: ["GeekWire Gala", "Seattle Startup Week"],
    reels: ["https://youtu.be/lena-lighthouse-reel"],
    photos: ["https://images.unsplash.com/photo-1529665253569-6d01c0eaf7b6"],
    notableClubs: ["Laughs Comedy Club", "Unexpected Productions"],
    instagram: "@lenalighthouse",
  },
];

for (const seed of comedianSeeds) {
  users.push({
    id: seed.id,
    name: seed.name,
    email: seed.email,
    hashedPassword: HASHED_PASSWORD,
    role: "COMEDIAN",
    createdAt: date(1, 11, 9),
    isPremium: seed.premium ?? false,
    premiumSince: seed.premium ? date(2, 1, 9) : null,
  });
}

const availabilityRecords: AvailabilityRecord[] = [];

const comedianProfiles: ComedianProfileRecord[] = comedianSeeds.map((seed, index) => {
  const availability: AvailabilityRecord[] = [
    {
      id: `avail-${seed.id}-fri`,
      userId: seed.id,
      date: iso(`2024-04-${String(5 + (index % 5) * 3).padStart(2, "0")}T00:00:00Z`),
      status: "free",
    },
    {
      id: `avail-${seed.id}-sat`,
      userId: seed.id,
      date: iso(`2024-04-${String(6 + (index % 5) * 3).padStart(2, "0")}T00:00:00Z`),
      status: "busy",
    },
  ];

  availabilityRecords.push(...availability);

  return {
    userId: seed.id,
    stageName: seed.stageName,
    bio: seed.bio,
    credits: seed.credits.join(", "),
    website: `https://www.${seed.stageName.toLowerCase().replace(/[^a-z]+/g, "-")}.com`,
    reelUrl: seed.reels[0] ?? null,
    instagram: seed.instagram ?? null,
    tiktokHandle: seed.tiktok ?? null,
    youtubeChannel: seed.youtube ?? null,
    travelRadiusMiles: 200,
    homeCity: seed.city,
    homeState: seed.state,
    styles: seed.styles,
    cleanRating: seed.cleanRating,
    rateMin: seed.rateMin,
    rateMax: seed.rateMax,
    reelUrls: seed.reels,
    photoUrls: seed.photos,
    notableClubs: seed.notableClubs,
    availability,
    createdAt: date(1, 12 + index, 9),
    updatedAt: date(3, 1 + index, 10),
  };
});

const comedianVideos: ComedianVideoRecord[] = comedianSeeds.flatMap((seed, index) => [
  {
    id: `video-${seed.id}-reel`,
    comedianUserId: seed.id,
    title: `${seed.stageName} showcase reel`,
    platform: "YOUTUBE",
    url: seed.reels[0],
    postedAt: date(2, 10 + index % 5, 18),
  },
  {
    id: `video-${seed.id}-clip`,
    comedianUserId: seed.id,
    title: `${seed.stageName} quick clip`,
    platform: "TIKTOK",
    url: `https://www.tiktok.com/@${seed.stageName.toLowerCase().replace(/[^a-z]+/g, "")}/video/${100000 + index * 1379}`,
    postedAt: date(3, 5 + (index % 4), 20),
  },
]);

const comedianAppearances: ComedianAppearanceRecord[] = comedianSeeds.flatMap((seed, index) => [
  {
    id: `appearance-${seed.id}-club`,
    comedianUserId: seed.id,
    showName: `${seed.stageName} Weekend Feature`,
    venueName: seed.notableClubs[0],
    city: seed.city,
    state: seed.state,
    performedAt: iso(`2023-${String(9 + (index % 3)).padStart(2, "0")}-15T03:00:00Z`),
    gigId: null,
  },
  {
    id: `appearance-${seed.id}-festival`,
    comedianUserId: seed.id,
    showName: `${seed.stageName} Festival Set`,
    venueName: seed.notableClubs.at(-1) ?? seed.notableClubs[0],
    city: seed.city,
    state: seed.state,
    performedAt: iso(`2023-${String(10 + (index % 3)).padStart(2, "0")}-20T04:00:00Z`),
    gigId: null,
  },
]);

const promoterProfiles: PromoterProfileRecord[] = [
  {
    userId: "user-promoter-seattle",
    organization: "Soundstage Productions",
    contactName: "Sasha Showcase",
    phone: "206-555-0100",
    website: "https://soundstageproductions.example.com",
    verificationStatus: "APPROVED",
    createdAt: date(1, 3, 10),
    updatedAt: date(3, 2, 9),
  },
  {
    userId: "user-promoter-portland",
    organization: "Rose City Comedy",
    contactName: "Parker PDX",
    phone: "503-555-0133",
    website: "https://rosecitycomedy.example.com",
    verificationStatus: "APPROVED",
    createdAt: date(1, 4, 11),
    updatedAt: date(3, 4, 9),
  },
  {
    userId: "user-promoter-tacoma",
    organization: "Grit City Laughs",
    contactName: "Taylor Tacoma",
    phone: "253-555-0199",
    website: "https://gritcitylaughs.example.com",
    verificationStatus: "PENDING",
    createdAt: date(1, 5, 12),
    updatedAt: date(2, 28, 9),
  },
  {
    userId: "user-promoter-olympia",
    organization: "Capitol Chuckles",
    contactName: "Oakley Olympia",
    phone: "360-555-0112",
    website: "https://capitolchuckles.example.com",
    verificationStatus: "APPROVED",
    createdAt: date(1, 6, 13),
    updatedAt: date(3, 6, 9),
  },
];

const venueProfiles: VenueProfileRecord[] = [
  {
    userId: "user-venue-seattle-laugh-lodge",
    venueName: "Laugh Lodge",
    address1: "123 Pike St",
    address2: null,
    city: "Seattle",
    state: "WA",
    postalCode: "98101",
    capacity: 220,
    contactEmail: "booking@laughlodge.example.com",
    phone: "206-555-0190",
    verificationStatus: "APPROVED",
    createdAt: date(1, 7, 14),
    updatedAt: date(3, 1, 10),
  },
  {
    userId: "user-venue-seattle-bay",
    venueName: "Bayfront Comedy",
    address1: "400 Alaskan Way",
    address2: "Suite 200",
    city: "Seattle",
    state: "WA",
    postalCode: "98104",
    capacity: 150,
    contactEmail: "hello@bayfrontcomedy.example.com",
    phone: "206-555-0191",
    verificationStatus: "APPROVED",
    createdAt: date(1, 7, 16),
    updatedAt: date(2, 20, 9),
  },
  {
    userId: "user-venue-portland-stumptown",
    venueName: "Stumptown Laugh Lab",
    address1: "88 Burnside St",
    address2: null,
    city: "Portland",
    state: "OR",
    postalCode: "97209",
    capacity: 180,
    contactEmail: "bookings@stumptownlaughlab.example.com",
    phone: "503-555-0108",
    verificationStatus: "APPROVED",
    createdAt: date(1, 8, 9),
    updatedAt: date(3, 3, 9),
  },
  {
    userId: "user-venue-portland-bridge",
    venueName: "Bridge City Comedy",
    address1: "500 Hawthorne Blvd",
    address2: null,
    city: "Portland",
    state: "OR",
    postalCode: "97214",
    capacity: 120,
    contactEmail: "info@bridgecitycomedy.example.com",
    phone: "503-555-0110",
    verificationStatus: "APPROVED",
    createdAt: date(1, 8, 11),
    updatedAt: date(2, 26, 9),
  },
  {
    userId: "user-venue-tacoma-grit",
    venueName: "Grit City Stage",
    address1: "777 Pacific Ave",
    address2: null,
    city: "Tacoma",
    state: "WA",
    postalCode: "98402",
    capacity: 200,
    contactEmail: "stage@gritcitystage.example.com",
    phone: "253-555-0117",
    verificationStatus: "PENDING",
    createdAt: date(1, 9, 10),
    updatedAt: date(2, 18, 9),
  },
  {
    userId: "user-venue-tacoma-waterfront",
    venueName: "Waterfront Comedy Loft",
    address1: "2 Dock St",
    address2: "Floor 3",
    city: "Tacoma",
    state: "WA",
    postalCode: "98402",
    capacity: 140,
    contactEmail: "booking@waterfrontloft.example.com",
    phone: "253-555-0124",
    verificationStatus: "APPROVED",
    createdAt: date(1, 9, 12),
    updatedAt: date(3, 5, 9),
  },
  {
    userId: "user-venue-olympia-capitol",
    venueName: "Capitol City Club",
    address1: "100 Capitol Way",
    address2: null,
    city: "Olympia",
    state: "WA",
    postalCode: "98501",
    capacity: 180,
    contactEmail: "hello@capitolcityclub.example.com",
    phone: "360-555-0152",
    verificationStatus: "APPROVED",
    createdAt: date(1, 10, 10),
    updatedAt: date(2, 15, 9),
  },
  {
    userId: "user-venue-olympia-brew",
    venueName: "Brew HaHa Hall",
    address1: "44 4th Ave",
    address2: null,
    city: "Olympia",
    state: "WA",
    postalCode: "98501",
    capacity: 90,
    contactEmail: "bookings@brewhahahall.example.com",
    phone: "360-555-0195",
    verificationStatus: "APPROVED",
    createdAt: date(1, 10, 12),
    updatedAt: date(3, 7, 9),
  },
];

const gigs: GigRecord[] = [
  {
    id: "gig-sea-clean-01",
    createdByUserId: "user-promoter-seattle",
    title: "Downtown Seattle Clean Showcase",
    description: "Friday showcase focused on clean corporate-ready material.",
    compensationType: "FLAT",
    payoutUsd: 60000,
    dateStart: iso("2024-04-12T20:00:00-07:00"),
    dateEnd: iso("2024-04-12T22:00:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Seattle",
    state: "WA",
    minAge: 18,
    isPublished: true,
    status: "PUBLISHED",
    format: "Showcase",
    setLengthMinutes: 20,
    audienceDescription: "Requires clean (PG-13 or cleaner) material for corporate partners.",
    totalSpots: 4,
    perks: ["Green room catering", "Professional photos"],
    createdAt: date(2, 12, 9),
    updatedAt: date(3, 20, 9),
  },
  {
    id: "gig-sea-late-02",
    createdByUserId: "user-venue-seattle-laugh-lodge",
    title: "Laugh Lodge Late Show",
    description: "Weekend late show looking for high-energy headliner.",
    compensationType: "FLAT",
    payoutUsd: 75000,
    dateStart: iso("2024-04-20T22:00:00-07:00"),
    dateEnd: iso("2024-04-21T00:00:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Seattle",
    state: "WA",
    minAge: 21,
    isPublished: true,
    status: "OPEN",
    format: "Club weekend",
    setLengthMinutes: 45,
    audienceDescription: "Late-night crowd open to edgy material.",
    totalSpots: 1,
    perks: ["Hotel provided", "Merch table"],
    createdAt: date(2, 15, 9),
    updatedAt: date(3, 18, 9),
  },
  {
    id: "gig-pdx-brew-01",
    createdByUserId: "user-promoter-portland",
    title: "Portland Brewery Comedy Night",
    description: "Monthly brewery show needs engaging feature acts.",
    compensationType: "DOOR_SPLIT",
    payoutUsd: 40000,
    dateStart: iso("2024-04-18T19:00:00-07:00"),
    dateEnd: iso("2024-04-18T21:00:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Portland",
    state: "OR",
    minAge: 21,
    isPublished: true,
    status: "PUBLISHED",
    format: "Brewery show",
    setLengthMinutes: 25,
    audienceDescription: "PG-13 friendly set requested for brewery partners.",
    totalSpots: 2,
    perks: ["Drink tickets", "Local press shoutout"],
    createdAt: date(2, 10, 9),
    updatedAt: date(3, 14, 9),
  },
  {
    id: "gig-pdx-club-02",
    createdByUserId: "user-venue-portland-stumptown",
    title: "Stumptown Laugh Lab Experimental Night",
    description: "Alternative comedy night, no clean requirement.",
    compensationType: "TIPS",
    payoutUsd: 15000,
    dateStart: iso("2024-05-02T20:00:00-07:00"),
    dateEnd: iso("2024-05-02T22:00:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Portland",
    state: "OR",
    minAge: 18,
    isPublished: true,
    status: "OPEN",
    format: "Alt showcase",
    setLengthMinutes: 15,
    audienceDescription: "Anything goes, supportive alt crowd.",
    totalSpots: 6,
    perks: ["Professional video", "Podcast interview"],
    createdAt: date(2, 20, 9),
    updatedAt: date(3, 25, 9),
  },
  {
    id: "gig-tac-corporate-01",
    createdByUserId: "user-promoter-tacoma",
    title: "Tacoma Tech Corporate Luncheon",
    description: "Corporate luncheon seeking clean MC and closer.",
    compensationType: "FLAT",
    payoutUsd: 95000,
    dateStart: iso("2024-03-22T12:00:00-07:00"),
    dateEnd: iso("2024-03-22T14:00:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Tacoma",
    state: "WA",
    minAge: 18,
    isPublished: true,
    status: "PUBLISHED",
    format: "Corporate",
    setLengthMinutes: 30,
    audienceDescription: "Strictly clean content for enterprise partners.",
    totalSpots: 1,
    perks: ["Travel stipend", "Post-event testimonials"],
    createdAt: date(2, 1, 9),
    updatedAt: date(3, 10, 9),
  },
  {
    id: "gig-tac-late-02",
    createdByUserId: "user-venue-tacoma-waterfront",
    title: "Waterfront Loft Late Night",
    description: "Saturday late show with rowdy crowd and DJ.",
    compensationType: "FLAT",
    payoutUsd: 65000,
    dateStart: iso("2024-04-27T22:30:00-07:00"),
    dateEnd: iso("2024-04-28T00:30:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Tacoma",
    state: "WA",
    minAge: 21,
    isPublished: true,
    status: "OPEN",
    format: "Club late night",
    setLengthMinutes: 30,
    audienceDescription: "Edgy material encouraged, crowd loves improv.",
    totalSpots: 2,
    perks: ["Hotel discount", "Drink tickets"],
    createdAt: date(2, 25, 9),
    updatedAt: date(3, 22, 9),
  },
  {
    id: "gig-oly-benefit-01",
    createdByUserId: "user-promoter-olympia",
    title: "Olympia Arts Benefit",
    description: "Fundraiser with families in attendance looking for clean headliner.",
    compensationType: "FLAT",
    payoutUsd: 70000,
    dateStart: iso("2024-03-30T18:00:00-07:00"),
    dateEnd: iso("2024-03-30T20:00:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Olympia",
    state: "WA",
    minAge: 12,
    isPublished: true,
    status: "PUBLISHED",
    format: "Fundraiser",
    setLengthMinutes: 35,
    audienceDescription: "Family friendly show supporting local arts.",
    totalSpots: 1,
    perks: ["Professional photos", "Local press"],
    createdAt: date(1, 28, 9),
    updatedAt: date(3, 12, 9),
  },
  {
    id: "gig-oly-brew-02",
    createdByUserId: "user-venue-olympia-brew",
    title: "Brew HaHa Comedy Night",
    description: "Monthly brewery show featuring regional comics.",
    compensationType: "DOOR_SPLIT",
    payoutUsd: 32000,
    dateStart: iso("2024-04-10T19:30:00-07:00"),
    dateEnd: iso("2024-04-10T21:30:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Olympia",
    state: "WA",
    minAge: 21,
    isPublished: true,
    status: "OPEN",
    format: "Brewery show",
    setLengthMinutes: 20,
    audienceDescription: "Looking for PG-13 hosts who can riff with beer lovers.",
    totalSpots: 3,
    perks: ["Brewery gift cards"],
    createdAt: date(2, 18, 9),
    updatedAt: date(3, 19, 9),
  },
  {
    id: "gig-bellingham-01",
    createdByUserId: "user-promoter-seattle",
    title: "Bellingham University Night",
    description: "Campus show needing youthful hosts and clean-ish material.",
    compensationType: "FLAT",
    payoutUsd: 50000,
    dateStart: iso("2024-03-08T19:00:00-08:00"),
    dateEnd: iso("2024-03-08T21:00:00-08:00"),
    timezone: "America/Los_Angeles",
    city: "Bellingham",
    state: "WA",
    minAge: 18,
    isPublished: true,
    status: "PUBLISHED",
    format: "Campus show",
    setLengthMinutes: 30,
    audienceDescription: "PG-13 requested, students love local references.",
    totalSpots: 2,
    perks: ["Campus meal vouchers"],
    createdAt: date(1, 25, 9),
    updatedAt: date(3, 5, 9),
  },
  {
    id: "gig-spokane-01",
    createdByUserId: "user-promoter-seattle",
    title: "Spokane Casino Weekend",
    description: "Weekend casino lounge seeking feature and closer.",
    compensationType: "FLAT",
    payoutUsd: 85000,
    dateStart: iso("2024-03-15T20:00:00-07:00"),
    dateEnd: iso("2024-03-16T22:00:00-07:00"),
    timezone: "America/Los_Angeles",
    city: "Airway Heights",
    state: "WA",
    minAge: 21,
    isPublished: true,
    status: "PUBLISHED",
    format: "Casino weekend",
    setLengthMinutes: 45,
    audienceDescription: "Prefers PG-13 with light crowd work.",
    totalSpots: 2,
    perks: ["Hotel suite", "Meal vouchers"],
    createdAt: date(1, 20, 9),
    updatedAt: date(3, 7, 9),
  },
];

interface BookingSeed {
  thread: ThreadRecord;
  messages: MessageRecord[];
  offer: OfferRecord;
  booking: BookingRecord;
  conversationReviews: ConversationReviewRecord[];
}

const bookingSeeds: BookingSeed[] = [
  {
    thread: {
      id: "thread-sea-clean-ella",
      gigId: "gig-sea-clean-01",
      createdById: "user-promoter-seattle",
      participantIds: ["user-promoter-seattle", "user-comedian-ella"],
      state: "BOOKED",
      lastMessageAt: date(3, 5, 18),
      createdAt: date(2, 18, 10),
      updatedAt: date(3, 5, 18),
    },
    messages: [
      {
        id: "msg-sea-clean-1",
        threadId: "thread-sea-clean-ella",
        senderId: "user-promoter-seattle",
        kind: "TEXT",
        body: "We'd love to have you headline our downtown clean showcase.",
        fileUrl: null,
        offerId: null,
        createdAt: date(2, 18, 10),
      },
      {
        id: "msg-sea-clean-2",
        threadId: "thread-sea-clean-ella",
        senderId: "user-comedian-ella",
        kind: "TEXT",
        body: "Thanks Sasha! Clean requirements work great for me.",
        fileUrl: null,
        offerId: null,
        createdAt: date(2, 18, 11),
      },
      {
        id: "msg-sea-clean-3",
        threadId: "thread-sea-clean-ella",
        senderId: "user-promoter-seattle",
        kind: "OFFER",
        body: null,
        fileUrl: null,
        offerId: "offer-sea-clean-ella",
        createdAt: date(2, 18, 12),
      },
      {
        id: "msg-sea-clean-4",
        threadId: "thread-sea-clean-ella",
        senderId: "user-comedian-ella",
        kind: "SYSTEM",
        body: "Offer accepted. Booking created: booking-sea-clean-ella",
        fileUrl: null,
        offerId: null,
        createdAt: date(3, 5, 18),
      },
    ],
    offer: {
      id: "offer-sea-clean-ella",
      threadId: "thread-sea-clean-ella",
      fromUserId: "user-promoter-seattle",
      amount: 65000,
      currency: "USD",
      terms: "35-minute clean headline set, includes photo meet-and-greet.",
      eventDate: iso("2024-04-12T20:00:00-07:00"),
      expiresAt: date(2, 28, 23),
      status: "ACCEPTED",
      createdAt: date(2, 18, 12),
    },
    booking: {
      id: "booking-sea-clean-ella",
      gigId: "gig-sea-clean-01",
      comedianId: "user-comedian-ella",
      promoterId: "user-promoter-seattle",
      offerId: "offer-sea-clean-ella",
      status: "PAID",
      payoutProtection: true,
      cancellationPolicy: "STANDARD",
      paymentIntentId: "pi_demo_clean_ella",
      createdAt: date(3, 5, 18),
    },
    conversationReviews: [
      {
        id: "conv-review-sea-clean-promoter",
        bookingId: "booking-sea-clean-ella",
        fromUserId: "user-promoter-seattle",
        toUserId: "user-comedian-ella",
        rating: 5,
        body: "Ella was responsive and sent promo assets immediately.",
        visible: true,
        createdAt: date(4, 13, 12),
      },
      {
        id: "conv-review-sea-clean-comic",
        bookingId: "booking-sea-clean-ella",
        fromUserId: "user-comedian-ella",
        toUserId: "user-promoter-seattle",
        rating: 5,
        body: "Sasha communicated every detail and the crowd was lovely.",
        visible: true,
        createdAt: date(4, 13, 12),
      },
    ],
  },
  {
    thread: {
      id: "thread-oly-benefit-kai",
      gigId: "gig-oly-benefit-01",
      createdById: "user-promoter-olympia",
      participantIds: ["user-promoter-olympia", "user-comedian-kai"],
      state: "BOOKED",
      lastMessageAt: date(2, 28, 19),
      createdAt: date(2, 10, 9),
      updatedAt: date(2, 28, 19),
    },
    messages: [
      {
        id: "msg-oly-benefit-1",
        threadId: "thread-oly-benefit-kai",
        senderId: "user-promoter-olympia",
        kind: "TEXT",
        body: "Hi Kai! Looking for a clean, friendly host for our arts benefit.",
        fileUrl: null,
        offerId: null,
        createdAt: date(2, 10, 9),
      },
      {
        id: "msg-oly-benefit-2",
        threadId: "thread-oly-benefit-kai",
        senderId: "user-comedian-kai",
        kind: "TEXT",
        body: "Sounds perfect. I can also help with audience warm-up games!",
        fileUrl: null,
        offerId: null,
        createdAt: date(2, 10, 10),
      },
      {
        id: "msg-oly-benefit-3",
        threadId: "thread-oly-benefit-kai",
        senderId: "user-promoter-olympia",
        kind: "OFFER",
        body: null,
        fileUrl: null,
        offerId: "offer-oly-benefit-kai",
        createdAt: date(2, 10, 11),
      },
      {
        id: "msg-oly-benefit-4",
        threadId: "thread-oly-benefit-kai",
        senderId: "user-comedian-kai",
        kind: "SYSTEM",
        body: "Offer accepted. Booking created: booking-oly-benefit-kai",
        fileUrl: null,
        offerId: null,
        createdAt: date(2, 28, 19),
      },
    ],
    offer: {
      id: "offer-oly-benefit-kai",
      threadId: "thread-oly-benefit-kai",
      fromUserId: "user-promoter-olympia",
      amount: 60000,
      currency: "USD",
      terms: "Host + 20-minute closing set, clean material only.",
      eventDate: iso("2024-03-30T18:00:00-07:00"),
      expiresAt: date(2, 29, 23),
      status: "ACCEPTED",
      createdAt: date(2, 10, 11),
    },
    booking: {
      id: "booking-oly-benefit-kai",
      gigId: "gig-oly-benefit-01",
      comedianId: "user-comedian-kai",
      promoterId: "user-promoter-olympia",
      offerId: "offer-oly-benefit-kai",
      status: "PAID",
      payoutProtection: true,
      cancellationPolicy: "FLEX",
      paymentIntentId: "pi_demo_oly_kai",
      createdAt: date(2, 28, 19),
    },
    conversationReviews: [
      {
        id: "conv-review-oly-benefit-promoter",
        bookingId: "booking-oly-benefit-kai",
        fromUserId: "user-promoter-olympia",
        toUserId: "user-comedian-kai",
        rating: 5,
        body: "Kai kept the families engaged and handled transitions perfectly.",
        visible: true,
        createdAt: date(3, 31, 12),
      },
      {
        id: "conv-review-oly-benefit-comic",
        bookingId: "booking-oly-benefit-kai",
        fromUserId: "user-comedian-kai",
        toUserId: "user-promoter-olympia",
        rating: 5,
        body: "Organized event with clear run-of-show. Happy to return!",
        visible: true,
        createdAt: date(3, 31, 12),
      },
    ],
  },
  {
    thread: {
      id: "thread-tac-corp-lena",
      gigId: "gig-tac-corporate-01",
      createdById: "user-promoter-tacoma",
      participantIds: ["user-promoter-tacoma", "user-comedian-lena"],
      state: "BOOKED",
      lastMessageAt: date(2, 20, 18),
      createdAt: date(1, 28, 9),
      updatedAt: date(2, 20, 18),
    },
    messages: [
      {
        id: "msg-tac-corp-1",
        threadId: "thread-tac-corp-lena",
        senderId: "user-promoter-tacoma",
        kind: "TEXT",
        body: "Hi Lena, need a clean closer for Tacoma Tech luncheon.",
        fileUrl: null,
        offerId: null,
        createdAt: date(1, 28, 9),
      },
      {
        id: "msg-tac-corp-2",
        threadId: "thread-tac-corp-lena",
        senderId: "user-comedian-lena",
        kind: "TEXT",
        body: "Would love to! I'll tailor to their engineering team.",
        fileUrl: null,
        offerId: null,
        createdAt: date(1, 28, 11),
      },
      {
        id: "msg-tac-corp-3",
        threadId: "thread-tac-corp-lena",
        senderId: "user-promoter-tacoma",
        kind: "OFFER",
        body: null,
        fileUrl: null,
        offerId: "offer-tac-corp-lena",
        createdAt: date(1, 28, 12),
      },
      {
        id: "msg-tac-corp-4",
        threadId: "thread-tac-corp-lena",
        senderId: "user-comedian-lena",
        kind: "SYSTEM",
        body: "Offer accepted. Booking created: booking-tac-corp-lena",
        fileUrl: null,
        offerId: null,
        createdAt: date(2, 20, 18),
      },
    ],
    offer: {
      id: "offer-tac-corp-lena",
      threadId: "thread-tac-corp-lena",
      fromUserId: "user-promoter-tacoma",
      amount: 90000,
      currency: "USD",
      terms: "30-minute clean keynote with Q&A",
      eventDate: iso("2024-03-22T12:00:00-07:00"),
      expiresAt: date(2, 1, 23),
      status: "ACCEPTED",
      createdAt: date(1, 28, 12),
    },
    booking: {
      id: "booking-tac-corp-lena",
      gigId: "gig-tac-corporate-01",
      comedianId: "user-comedian-lena",
      promoterId: "user-promoter-tacoma",
      offerId: "offer-tac-corp-lena",
      status: "PAID",
      payoutProtection: true,
      cancellationPolicy: "STRICT",
      paymentIntentId: "pi_demo_tac_lena",
      createdAt: date(2, 20, 18),
    },
    conversationReviews: [
      {
        id: "conv-review-tac-corp-promoter",
        bookingId: "booking-tac-corp-lena",
        fromUserId: "user-promoter-tacoma",
        toUserId: "user-comedian-lena",
        rating: 5,
        body: "Lena delivered polished material and handled exec banter flawlessly.",
        visible: true,
        createdAt: date(3, 23, 12),
      },
      {
        id: "conv-review-tac-corp-comic",
        bookingId: "booking-tac-corp-lena",
        fromUserId: "user-comedian-lena",
        toUserId: "user-promoter-tacoma",
        rating: 4,
        body: "Taylor was organized though AV check ran tight.",
        visible: true,
        createdAt: date(3, 23, 12),
      },
    ],
  },
  {
    thread: {
      id: "thread-bham-isa",
      gigId: "gig-bellingham-01",
      createdById: "user-promoter-seattle",
      participantIds: ["user-promoter-seattle", "user-comedian-isa"],
      state: "BOOKED",
      lastMessageAt: date(2, 15, 18),
      createdAt: date(1, 30, 9),
      updatedAt: date(2, 15, 18),
    },
    messages: [
      {
        id: "msg-bham-1",
        threadId: "thread-bham-isa",
        senderId: "user-promoter-seattle",
        kind: "TEXT",
        body: "Looking for someone who can connect with students—interested?",
        fileUrl: null,
        offerId: null,
        createdAt: date(1, 30, 9),
      },
      {
        id: "msg-bham-2",
        threadId: "thread-bham-isa",
        senderId: "user-comedian-isa",
        kind: "TEXT",
        body: "Absolutely. I'll bring campus-specific material.",
        fileUrl: null,
        offerId: null,
        createdAt: date(1, 30, 10),
      },
      {
        id: "msg-bham-3",
        threadId: "thread-bham-isa",
        senderId: "user-promoter-seattle",
        kind: "OFFER",
        body: null,
        fileUrl: null,
        offerId: "offer-bham-isa",
        createdAt: date(1, 30, 11),
      },
      {
        id: "msg-bham-4",
        threadId: "thread-bham-isa",
        senderId: "user-comedian-isa",
        kind: "SYSTEM",
        body: "Offer accepted. Booking created: booking-bham-isa",
        fileUrl: null,
        offerId: null,
        createdAt: date(2, 15, 18),
      },
    ],
    offer: {
      id: "offer-bham-isa",
      threadId: "thread-bham-isa",
      fromUserId: "user-promoter-seattle",
      amount: 52000,
      currency: "USD",
      terms: "Host + 25-minute featured set, PG-13.",
      eventDate: iso("2024-03-08T19:00:00-08:00"),
      expiresAt: date(2, 10, 23),
      status: "ACCEPTED",
      createdAt: date(1, 30, 11),
    },
    booking: {
      id: "booking-bham-isa",
      gigId: "gig-bellingham-01",
      comedianId: "user-comedian-isa",
      promoterId: "user-promoter-seattle",
      offerId: "offer-bham-isa",
      status: "PAID",
      payoutProtection: true,
      cancellationPolicy: "STANDARD",
      paymentIntentId: "pi_demo_bham_isa",
      createdAt: date(2, 15, 18),
    },
    conversationReviews: [
      {
        id: "conv-review-bham-promoter",
        bookingId: "booking-bham-isa",
        fromUserId: "user-promoter-seattle",
        toUserId: "user-comedian-isa",
        rating: 4,
        body: "Isa kept the show moving and was easy to work with.",
        visible: true,
        createdAt: date(3, 9, 12),
      },
      {
        id: "conv-review-bham-comic",
        bookingId: "booking-bham-isa",
        fromUserId: "user-comedian-isa",
        toUserId: "user-promoter-seattle",
        rating: 5,
        body: "Great crowd and smooth campus logistics!",
        visible: true,
        createdAt: date(3, 9, 12),
      },
    ],
  },
];

const threads: ThreadRecord[] = bookingSeeds.map((seed) => seed.thread);
const messages: MessageRecord[] = bookingSeeds.flatMap((seed) => seed.messages);
const offers: OfferRecord[] = bookingSeeds.map((seed) => seed.offer);
const bookings: BookingRecord[] = bookingSeeds.map((seed) => seed.booking);
const conversationReviews: ConversationReviewRecord[] = bookingSeeds.flatMap(
  (seed) => seed.conversationReviews,
);

const reviewAuthors = [
  "user-promoter-seattle",
  "user-promoter-portland",
  "user-promoter-tacoma",
  "user-promoter-olympia",
  "user-venue-seattle-laugh-lodge",
  "user-venue-portland-stumptown",
  "user-venue-olympia-brew",
  "user-comedian-ava",
  "user-comedian-ben",
  "user-comedian-cara",
  "user-comedian-diego",
  "user-comedian-fern",
  "user-comedian-gabe",
  "user-comedian-hana",
  "user-comedian-isa",
  "user-comedian-jules",
  "user-comedian-kai",
  "user-comedian-lena",
  "user-venue-tacoma-waterfront",
  "user-comedian-ella",
];

const bookedGigIds = bookings.map((booking) => booking.gigId);

const reviews: ReviewRecord[] = Array.from({ length: 20 }).map((_, index) => {
  const gigId = bookedGigIds[index % bookedGigIds.length];
  const booking = bookings.find((entry) => entry.gigId === gigId)!;
  const authorUserId = reviewAuthors[index];
  const subjectUserId =
    booking.comedianId === authorUserId ? booking.promoterId : booking.comedianId;

  return {
    id: `review-${index + 1}`,
    authorUserId,
    subjectUserId,
    gigId,
    rating: ((index % 5) + 1) as ReviewRecord["rating"],
    comment: `Loved the energy and professionalism during ${gigId}. ${
      index % 2 === 0 ? "Would book again." : "Crowd had a blast."
    }`,
    visible: true,
    createdAt: iso(`2024-04-${String(2 + index).padStart(2, "0")}T12:00:00Z`),
  };
});

const adSlots: AdSlotRecord[] = [
  {
    id: "ad-home-hero",
    page: "home",
    placement: "top",
    html: "<div class=\"ad-creative\">\n  <h3>PNW Laugh Fest</h3>\n  <p>Grab VIP passes before they're gone.</p>\n</div>",
    imageUrl: undefined,
    linkUrl: "https://pnwlaughfest.example.com",
    active: true,
    priority: 1,
    createdAt: date(2, 1, 9),
    updatedAt: date(3, 1, 9),
  },
  {
    id: "ad-search-sidebar",
    page: "search",
    placement: "sidebar",
    html: undefined,
    imageUrl: "https://images.unsplash.com/photo-1472653816316-3ad6f10a6592",
    linkUrl: "https://thefunny.local/promo/premium",
    active: true,
    priority: 2,
    createdAt: date(2, 5, 9),
    updatedAt: date(3, 4, 9),
  },
  {
    id: "ad-profile-inline",
    page: "profile",
    placement: "inline",
    html: "<div class=\"ad-creative\">\n  <strong>Need merch?</strong> Partner with PNW Print House.\n</div>",
    imageUrl: undefined,
    linkUrl: "https://pnwprinthouse.example.com",
    active: true,
    priority: 3,
    createdAt: date(2, 7, 9),
    updatedAt: date(3, 6, 9),
  },
];

const featureFlags = Object.entries(getDefaultFeatureFlags()).map(([key, enabled]) => ({
  key: key as FeatureFlagKey,
  enabled,
  updatedAt: date(2, 1, 9),
}));

async function main(): Promise<void> {
  const snapshot: DatabaseSnapshot = {
    users,
    comedianProfiles,
    comedianVideos,
    comedianAppearances,
    promoterProfiles,
    venueProfiles,
    gigs,
    applications: [],
    verificationRequests: [],
    favorites: [],
    threads,
    messages,
    offers,
    bookings,
    conversationReviews,
    reviews,
    reviewReminders: [],
    availability: availabilityRecords,
    reports: [],
    communityBoardMessages: [],
    adSlots,
    featureFlags,
  };

  await fs.mkdir(path.dirname(DATA_PATH), { recursive: true });
  await fs.writeFile(DATA_PATH, JSON.stringify(snapshot, null, 2));
  // eslint-disable-next-line no-console
  console.log(`Seeded demo data to ${DATA_PATH}`);
}

main().catch((error) => {
  // eslint-disable-next-line no-console
  console.error("Failed to seed data", error);
  process.exit(1);
});

